# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-27 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Please enter the category name.', max_length=128, unique=True),
        ),
    ]
